name: Pull Request Workflow

on:
  pull_request:
    types: [opened]

jobs:
  print_pr_title:
    runs-on: ubuntu-latest

    name: Print Pull Request Title
    steps:
    - run: echo "${{ github.event.pull_request.title }}"
